export const userConstants= {
    LOGIN:'LOGIN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    REGISTER:'REGISTER',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',
    LOGOUT:'LOGOUT',
    LOGIN_ERROR:'LOGIN_ERROR',
    GET_USER:'GET_USER',
    GET_USER_SUCCESS:'GET_USER_SUCCESS',
}